# Generated by Django 4.2.29 on 2026-03-14 15:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matching', '0002_seed_problem_statements'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_text', models.TextField(blank=True, max_length=280)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='matching.connection')),
            ],
        ),
        migrations.CreateModel(
            name='FeaturedMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('featured_from', models.DateField(auto_now_add=True)),
                ('featured_until', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=500)),
                ('featured_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_by_me', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
