# Generated by Django 4.2.29 on 2026-03-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_matchfeedback_featuredmember'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['requester', 'status'], name='matching_co_request_c73638_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['recipient', 'status'], name='matching_co_recipie_4cd9bc_idx'),
        ),
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['status', 'updated_at'], name='matching_co_status_1c244c_idx'),
        ),
    ]
