# Generated by Django 4.2.29 on 2026-03-13 17:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nces_id', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=2)),
                ('locale_type', models.CharField(choices=[('URBAN', 'Urban'), ('SUBURBAN', 'Suburban'), ('RURAL', 'Rural'), ('TOWN', 'Town')], max_length=10)),
                ('enrollment', models.PositiveIntegerField()),
                ('frl_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ell_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('data_vintage', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
