# Generated by Django 4.2.29 on 2026-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_MESSAGE', 'New Message'), ('CONNECTION_REQUEST', 'Connection Request'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('STAFF_JOINED', 'Staff Joined'), ('FEEDBACK_PROMPT', 'Feedback Prompt')], max_length=30),
        ),
    ]
